package com.jack.spring.jdbc;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

public class JdbcTemplateTest {
	private static JdbcTemplate jdbcTemplate;
	@BeforeClass
	public static void setup(){
		String url ="jdbc:hsqldb:men:test";
		String username="sa";
		String password ="";
		
		DriverManagerDataSource dataSource = new DriverManagerDataSource(url, username, password);
		
		dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
		jdbcTemplate=new JdbcTemplate(dataSource);
		String createTableSql = "create memory table test" + "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + "name varchar(100))";  
		   jdbcTemplate.update(createTableSql); 
	}
	@Test
	public void test(){
		String sql = "select * from test";  
		jdbcTemplate.query(sql, new RowCallbackHandler() {
			
			@Override
			public void processRow(ResultSet rs) throws SQLException {
				// TODO Auto-generated method stub
				 String value = rs.getString("TABLE_NAME");  
	             System.out.println("Column TABLENAME:" + value);  
			}
		});
	}
}
